- Gemfile
- Gemfile.lock
- app/models/user.rb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20220815060526_devise_create_users.rb
- db/schema.rb
- test/models/user_test.rb
I added a user model and configred some things.
> added user model

- Gemfile.lock
- app/models/vinyl.rb
- db/migrate/20220815055435_create_vinyls.rb
- test/models/vinyl_test.rb
please have a look at the vinyl model and migration file
> created vinyl model

- Gemfile.lock
- app/models/booking.rb
- app/models/offer.rb
- db/migrate/20220815062641_create_offers.rb
- db/migrate/20220815063348_create_bookings.rb
- db/schema.rb
- test/models/booking_test.rb
- test/models/offer_test.rb
bookings and offer model generated
> Bookings model

- app/controllers/offers_controller.rb
- test/controllers/offers_controller_test.rb
added a new controller - offers
> added offer controller

- app/models/booking.rb
- app/models/offer.rb
- app/models/user.rb
- app/models/vinyl.rb
Added some basic validations and associations to all models
> Validations and associations

- db/seeds.rb
> added bookings seed. The title of this branch is a mistake

- app/models/booking.rb
- app/models/offer.rb
- app/models/user.rb
- db/migrate/20220815091638_add_default_status_to_bookings.rb
- db/schema.rb
added default for bookings status
> Extra associations

- app/controllers/vinyls_controller.rb
- app/views/vinyls/index.html.erb
- app/views/vinyls/show.html.erb
- config/routes.rb
- test/controllers/vinyls_controller_test.rb
Created VinylController with only index and show function. Also added the index and show pages for vinyls with basic start up code.
> Vinyl Controller creation 

- app/models/booking.rb
- app/models/offer.rb
- app/models/user.rb
- app/models/vinyl.rb
please check the validations i added, thank you xoxo
> added additional validations to all four models

- app/views/vinyls/index.html.erb
- db/migrate/20220816030333_add_image_to_vinyls.rb
- db/schema.rb
- db/seeds.rb
seeder works now with images and vinyl index page displays images
> Images in Seeder

- app/views/offers/index.html.erb
- app/views/offers/show.html.erb
> added the index offer page

- app/controllers/bookings_controller.rb
- app/policies/booking_policy.rb
- app/policies/offer_policy.rb
- app/views/bookings/index.html.erb
> Pundit creation

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_vinyl_card.scss
- app/assets/stylesheets/config/_general.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
how do you like my masterpiece?
> fixed landing page back and front end

- app/views/shared/_navbar.html.erb
- config/routes.rb
added navigation and routes and logo nav
> Add nav buttons

- app/controllers/bookings_controller.rb
> fixed form redirect

- app/controllers/bookings_controller.rb
- app/controllers/offers_controller.rb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_navbar.html.erb
Added all vinyl navigation and container to login page
> modified nav bar and container to login

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_vinyl_card.scss
- app/assets/stylesheets/pages/_bookings.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/controllers/application_controller.rb
- app/views/bookings/index.html.erb
- app/views/shared/_navbar.html.erb
> bookings index page css completed mate

- app/assets/stylesheets/components/_vinyl_card.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/vinyls/index.html.erb
> fixed vinyl index page

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_navbar.html.erb
> Nav center

- app/views/layouts/application.html.erb
removed favicon from application.html.erb
> removed favicon

- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> nav bar resizing

- app/assets/stylesheets/components/_vinyl_card.scss
- app/controllers/bookings_controller.rb
- app/policies/booking_policy.rb
- app/views/bookings/index.html.erb
- config/routes.rb
Added delete function to bookings, NOT offers
> added delete function to bookings

- app/assets/config/manifest.js
- app/controllers/offers_controller.rb
- app/javascript/controllers/map_controller.js
- app/views/offers/_popup.html.erb
please check if there's conflict...
> map style changed

- app/assets/stylesheets/components/_delete.scss
- app/controllers/bookings_controller.rb
- app/controllers/offers_controller.rb
- app/views/bookings/index.html.erb
- app/views/shared/_flashes.html.erb
added alerts for delete/new/update and styled in css
> alerts for actions

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_utilities.scss
- app/policies/offer_policy.rb
- app/views/bookings/index.html.erb
fixed footer on bookings page so actually stays at the bottom
> fixed footer on bookings page

- app/views/shared/_navbar.html.erb
> removre navbar

- app/views/shared/_navbar.html.erb
all vinyls page is viewable for users not logged in
> navbar access to all vinyls

- app/views/bookings/index.html.erb
adjusted height on cards on show bookings page
> accept buttons

- app/views/bookings/index.html.erb
> footer fix

- app/assets/stylesheets/components/_vinyl_card.scss
- app/views/vinyls/index.html.erb
> fixed vinyl cards

- app/views/pages/home.html.erb
> purple search button

- app/assets/stylesheets/components/_offer_card.scss
- app/assets/stylesheets/pages/_vinyl_offers.scss
- app/views/pages/home.html.erb
- app/views/vinyls/show.html.erb
> fixed show page layout

- app/assets/stylesheets/components/_navbar.scss
> added purple hover
